language: cpp

matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
    - os: osx
      sudo: false
      osx_image: xcode7.3

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - qt5-default
      - libqt5opengl5-dev
      - xorg-dev
      - lib32stdc++6 # For CMake

cache:
  directories:
    - $HOME/.local

install: ./.travis-deps.sh
script: ./.travis-build.sh
after_success: ./.travis-upload.sh

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file_glob: true
  file: ${HOME}/build/${TRAVIS_REPO_SLUG}/artifacts/*.tar.xz
  skip_cleanup: true
  on:
    branch: master
